language: java
sudo: false
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
       - $HOME/.m2

# use operating systems.
os:
  - linux

jdk:
  - oraclejdk8

# setup jobs.
env:
  - USE_FRAMEBUFFER=true
  - USE_FRAMEBUFFER=false _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

# run on xvfb screen.
before_install:
  - if [ $USE_FRAMEBUFFER = "true" ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start; fi

# skip install stage.
install: true

script:
  - jdk_switcher use oraclejdk8
  - mvn test -f ./source/pom.xml

after_success:
  - cd source
  - mvn clean test cobertura:cobertura coveralls:report